kind: Service
apiVersion: v1
metadata:
  name: vprocache01
spec:
  selector:
    app: vpromc
  type: ClusterIP
  ports:
    - name: vprocache-port
      port: 11211
      targetPort: vpromc-port
      protocol: TCP
