apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro-db
  labels:
    app: vpro-db

spec:
  selector:
    matchLabels:
      app: vpro-db
  replicas: 1
  template:
    metadata:
      labels:
        app: vpro-db
    spec:
      containers:
        - name: vpro-db
          image: imranvisualpath/vprdbfix
          args:
            - "ignore-db-dir=lost+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - name: vpro-db-port
              containerPort: 3306
          env:
            - name: MY_SQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db-pass
      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-083960a989bfdffd1
            fsType: ext4
