apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro-db
  labels:
    app: vpro-db

spec:
  selector:
    matchLabels:
      app: vpro-db
  replicas: 1
  template:
    metadata:
      labels:
        app: vpro-db
    spec:
      containers:
        - name: vpro-db
          image: imranvisualpath/vprdbfix
          args:
            - "ignore-db-dir=lost+found"
          ports:
            - name: vpro-db-port
              containerPort: 3306
          env:
            - name: MY_SQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db-pass
